id: P001816
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 2021-12-17 10:23:13.725973
source_metadata:
  id: bdr:W21686
  title: གཅུང་དོན་ཡོད་དང་དོན་གྲུབ་ཀྱི་རྣམ་ཐར་དད་པའི་པདྨོ་འཛུམ་པའི་ཉིན་བྱེད།
  author: ''
  volumes:
    76d38e97330e49d7bb017045cda66802:
      image_group_id: I1KG13083
      title: ''
      volume_number: 1
      total_pages: 110
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
